name: PR Message Checkout

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  contents: read

jobs:
  check:
    name : Check PR title
    runs-on: ubuntu-latest 
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@master
        with:
            allowed_prefixes: 'Patch:,Feature:,Breaking:' # title should start with the given prefix
            prefix_case_sensitive: true # title prefix are case sensitive
            min_length: 5 # Min length of the title
            github_token: ${{ github.token }}