name: PR Message Checkout

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  contents: read

concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name : Check PR title
    runs-on: ubuntu-latest 
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@master
        with:
            allowed_prefixes: 'Patch:,Feature:,Breaking:' # title should start with the given prefix
            prefix_case_sensitive: true # title prefix are case sensitive
            min_length: 5 # Min length of the title
            github_token: ${{ github.token }}